---
apiVersion: v1
kind: Service
metadata:
  name: smart-api
  labels:
    app: smart-api
    service: smart-api
spec:
  ports:
  - port: 8000
    name: http
    protocol: TCP
  selector:
    app: smart-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-api-v1
  labels:
    app: smart-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-api
      version: v1
  template:
    metadata:
      labels:
        app: smart-api
        version: v1
    spec:
      containers:
      - name: smart-api
        image: registry.cn-beijing.aliyuncs.com/sunwenbo/smart-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: smart-api-config
          mountPath: /home/service/config/
          readOnly: true
      volumes:
      - name: smart-api-config
        configMap:
          name: settings
