settings:
  application:
    # dev开发环境 test测试环境 prod线上环境  demo
    mode: dev
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    name: smart-api
    # 端口号
    port: 8000 # 服务端口号
    readtimeout: 1
    writertimeout: 2
    # 数据权限功能开关
    enabledp: true
  ssl:
    keystr: ''
    pem: ''
    enable: false
    domain: ''
  logger:
    # 日志存放路径
    path: logs/
    # 日志输出，file：文件，default：命令行，其他：命令行
    stdout: 'default' #控制台日志，启用后，不输出到文件
    # 日志等级, trace, debug, info, warn, error, fatal
    level: trace
    # 数据库日志开关,开启后将记录操作日志到数据库sys_opera_log表
    enableddb: false
  jwt:
    # token 密钥，生产环境时记得修改
    secret: smart-api
    # token 过期时间 单位：秒
    timeout: 3600
  database:
    # 数据库类型 mysql, sqlite3, postgres, sqlserver
    # sqlserver: sqlserver://用户名:密码@地址?database=数据库名
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: root:sunwenbo@tcp(127.0.0.1:3306)/smart-api?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
#  databases:
#    'locaohost:8000':
#      driver: mysql
#        # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
#        source: user:password@tcp(127.0.0.1:3306)/dbname?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
#      registers:
#        - sources:
#            - user:password@tcp(127.0.0.1:3306)/dbname?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  gen:
    # 代码生成读取的数据库名称
    dbname: smart-api
    # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
    frontpath: ../smart-ui/src
  extend: # 扩展项使用说明
    ldap:
      tls: false
      # 设置LDAP服务器地址和端口
      host: ""
      port: 389
      # LDAP管理员账号
      bindDN: ""
      # LDAP管理员密码
      bindPassword: ""
      # LDAP查询域
      searchDomain: ""
    notify:
      botCredit:
        appId: ""
        appSecret: ""
    aesSecrets:
      key: "your-secret-keys"
  cache:
#    redis:
#      addr: 127.0.0.1:6379
#      password: xxxxxx
#      db: 2
    # key存在即可
    memory: ''
  queue:
    memory:
      poolSize: 100
#    redis:
#      addr: 127.0.0.1:6379
#      password: xxxxxx
#      producer:
#        streamMaxLength: 100
#        approximateMaxLength: true
#      consumer:
#        visibilityTimeout: 60
#        bufferSize: 100
#        concurrency: 10
#        blockingTimeout: 5
#        reclaimInterval: 1
  locker:
    redis:
